server:
    port: 9080
spring:
    application:
        name: spring_security_jwt
    datasource:
        url: jdbc:mysql://localhost:3306/jwt
        username: root
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl:
                auto: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

